### ISSUE TITLE
sample data error

### ISSUE THREAD

**Issue by chili-chiu** [sylvainprigent/napari-sairyscan#1]
Click on File > Open sample > napari-Sairyscan resulted in the following error: 

FileExistsError: [Errno Cannot find the file:] /opt/anaconda3/envs/napari-latest/lib/python3.9/site-packages/sairyscan/data/celegans_airyscan.czi

**Comment by sylvainprigent** [comment]
data were missing in the sairyscan pip package. It is now fixed in the version 0.0.2
